import React from "react";
import mainlogo from "../assets/70067.png";
import bklogo from "../assets/85936.png";
import mclogo from "../assets/35939.png";
import wendyslogo from "../assets/39412.jpg";
import sslogo from "../assets/538755.jpg";
import habitlogo from "../assets/The-Habit-Burger-Grill.png";

const data = [
  // IN-N-OUT -----------------------------------------------------------------------
  {
    name: "In-N-Out",
    logo: mainlogo,
    description: "info IN-N-OUT",
    option: {
      nutrition: [
        {
          name: "Hamburger",
          serving: "243",
          cal: "390",
          fat: "19",
          cholesterol: "40",
          sodium: "650",
          carbs: "39",
          sugars: "10",
          protein: "16",
        },
        {
          name: "Cheeseburger",
          serving: "268",
          cal: "480",
          fat: "27",
          cholesterol: "60",
          sodium: "1000",
          carbs: "39",
          sugars: "10",
          protein: "22",
        },
        {
          name: "Double Double",
          serving: "330",
          cal: "670",
          fat: "41",
          cholesterol: "120",
          sodium: "1440",
          carbs: "39",
          sugars: "10",
          protein: "37",
        },
        {
          name: "Fries",
          serving: "125",
          cal: "370",
          fat: "15",
          cholesterol: "0",
          sodium: "250",
          carbs: "52",
          sugars: "0",
          protein: "6",
        },
        {
          name: "Vanilla Shake",
          serving: "15 oz.",
          cal: "570",
          fat: "30",
          cholesterol: "120",
          sodium: "360",
          carbs: "65",
          sugars: "50",
          protein: "10",
        },
      ],
      cost: [
        {
          name: "",
          price: "",
          serving: "",
          cal: "",
          fat: "",
          cholesterol: "",
          sodium: "",
          carbs: "",
          sugars: "",
          protein: "",
        },
      ],
    },
  },
  // MCDONALD'S -----------------------------------------------------------------------
  {
    name: "McDonald's",
    logo: mclogo,
    desription: "info McDonald's",
    option: {
      nutrition: [
        {
          name: "Hamburger",
          serving: "100",
          cal: "250",
          fat: "9",
          cholesterol: "25",
          sodium: "520",
          carbs: "31",
          sugars: "6",
          protein: "12",
        },
        {
          name: "Cheeseburger",
          serving: "114",
          cal: "300",
          fat: "12",
          cholesterol: "40",
          sodium: "750",
          carbs: "33",
          sugars: "6",
          protein: "15",
        },
        {
          name: "Double Cheeseburger",
          serving: "165",
          cal: "210",
          fat: "23",
          cholesterol: "80",
          sodium: "1150",
          carbs: "34",
          sugars: "7",
          protein: "25",
        },
        {
          name: "Medium Fries",
          serving: "117",
          cal: "380",
          fat: "19",
          cholesterol: "0",
          sodium: "270",
          carbs: "48",
          sugars: "0",
          protein: "4",
        },
        {
          name: "Vanilla Shake",
          serving: "16 oz.",
          cal: "680",
          fat: "20",
          cholesterol: "60",
          sodium: "220",
          carbs: "111",
          sugars: "82",
          protein: "14",
        },
      ],
      cost: [
        {
          name: "",
          price: "",
          serving: "",
          cal: "",
          fat: "",
          cholesterol: "",
          sodium: "",
          carbs: "",
          sugars: "",
          protein: "",
        },
      ],
    },
  },
  // BURGER KING -----------------------------------------------------------------------
  {
    name: "Burger King",
    logo: bklogo,
    description: "info Burger King",
    option: {
      nutrition: [
        {
          name: "WHOPPER",
          serving: "270",
          cal: "660",
          fat: "40",
          cholesterol: "N/A",
          sodium: "980",
          carbs: "49",
          sugars: "11",
          protein: "28",
        },
        {
          name: "WHOPPER w/ Cheese",
          serving: "292",
          cal: "740",
          fat: "46",
          cholesterol: "N/A",
          sodium: "1340",
          carbs: "50",
          sugars: "11",
          protein: "32",
        },
        {
          name: "DOUBLE WHOPPER w/ Cheese",
          serving: "377",
          cal: "980",
          fat: "64",
          cholesterol: "N/A",
          sodium: "1410",
          carbs: "50",
          sugars: "11",
          protein: "35",
        },
        {
          name: "Medium Fries",
          serving: "153",
          cal: "380",
          fat: "16",
          cholesterol: "N/A",
          sodium: "360",
          carbs: "58",
          sugars: "1",
          protein: "4",
        },
        {
          name: "Hershey Sundae Pie",
          serving: "79",
          cal: "310",
          fat: "19",
          cholesterol: "N/A",
          sodium: "220",
          carbs: "32",
          sugars: "22",
          protein: "3",
        },
      ],
      cost: [
        {
          name: "",
          price: "",
          serving: "",
          cal: "",
          fat: "",
          cholesterol: "",
          sodium: "",
          carbs: "",
          sugars: "",
          protein: "",
        },
      ],
    },
  },
  // WENDY'S -----------------------------------------------------------------------
  {
    name: "Wendy's",
    logo: wendyslogo,
    description: "info Wendy's",
    option: {
      nutrition: [
        {
          name: "Dave's Single",
          serving: "N/A",
          cal: "570",
          fat: "34",
          cholesterol: "N/A",
          sodium: "N/A",
          carbs: "39",
          sugars: "N/A",
          protein: "30",
        },
        {
          name: "Dave's Single",
          serving: "N/A",
          cal: "570",
          fat: "34",
          cholesterol: "N/A",
          sodium: "N/A",
          carbs: "39",
          sugars: "N/A",
          protein: "30",
        },
        {
          name: "Dave's Double",
          serving: "N/A",
          cal: "810",
          fat: "51",
          cholesterol: "N/A",
          sodium: "N/A",
          carbs: "39",
          sugars: "N/A",
          protein: "49",
        },
        {
          name: "Medium Fries",
          serving: "N/A",
          cal: "420",
          fat: "19",
          cholesterol: "N/A",
          sodium: "N/A",
          carbs: "56",
          sugars: "N/A",
          protein: "6",
        },
        {
          name: "Vanilla Frosty",
          serving: "N/A",
          cal: "460",
          fat: "12",
          cholesterol: "N/A",
          sodium: "N/A",
          carbs: "77",
          sugars: "N/A",
          protein: "12",
        },
      ],
      cost: [
        {
          name: "",
          price: "",
          serving: "",
          cal: "",
          fat: "",
          cholesterol: "",
          sodium: "",
          carbs: "",
          sugars: "",
          protein: "",
        },
      ],
    },
  },
  // SHAKE SHACK -----------------------------------------------------------------------
  {
    name: "Shake Shack",
    logo: sslogo,
    description: "info shake shack",
    option: {
      nutrition: [
        {
          name: "Single Hamburger",
          serving: "N/A",
          cal: "370",
          fat: "18",
          cholesterol: "75",
          sodium: "850",
          carbs: "24",
          sugars: "5",
          protein: "N/A",
        },
        {
          name: "Single Cheeseburger",
          serving: "N/A",
          cal: "440",
          fat: "24",
          cholesterol: "95",
          sodium: "1200",
          carbs: "25",
          sugars: "5",
          protein: "N/A",
        },
        {
          name: "Double Cheeseburger",
          serving: "N/A",
          cal: "700",
          fat: "42",
          cholesterol: "175",
          sodium: "2200",
          carbs: "49",
          sugars: "5",
          protein: "N/A",
        },
        {
          name: "Regular Fries",
          serving: "N/A",
          cal: "470",
          fat: "22",
          cholesterol: "15",
          sodium: "740",
          carbs: "63",
          sugars: "1",
          protein: "N/A",
        },
        {
          name: "Vanilla Shake",
          serving: "N/A",
          cal: "680",
          fat: "36",
          cholesterol: "235",
          sodium: "430",
          carbs: "72",
          sugars: "71",
          protein: "N/A",
        },
      ],
      cost: [
        {
          name: "",
          price: "",
          serving: "",
          cal: "",
          fat: "",
          cholesterol: "",
          sodium: "",
          carbs: "",
          sugars: "",
          protein: "",
        },
      ],
    },
  },
  // THE HABIT -----------------------------------------------------------------------
  {
    name: "The Habit",
    logo: habitlogo,
    description: "info habit",
    option: {
      nutrition: [
        {
          name: "Charburger",
          serving: "260",
          cal: "470",
          fat: "35",
          cholesterol: "75",
          sodium: "1240",
          carbs: "35",
          sugars: "4",
          protein: "20",
        },
        {
          name: "Teriyaki Charburger",
          serving: "300",
          cal: "510",
          fat: "35",
          cholesterol: "65",
          sodium: "1610",
          carbs: "52",
          sugars: "16",
          protein: "23",
        },
        {
          name: "Double Charburger",
          serving: "320",
          cal: "640",
          fat: "55",
          cholesterol: "120",
          sodium: "2130",
          carbs: "35",
          sugars: "8",
          protein: "39",
        },
        {
          name: "French Fries",
          serving: "5.5 oz",
          cal: "440",
          fat: "27",
          cholesterol: "0",
          sodium: "360",
          carbs: "100",
          sugars: "1",
          protein: "4",
        },
        {
          name: "Vanilla Shake",
          serving: "16 oz",
          cal: "710",
          fat: "30",
          cholesterol: "100",
          sodium: "820",
          carbs: "60",
          sugars: "80",
          protein: "14",
        },
      ],
      cost: [
        {
          name: "",
          price: "",
          serving: "",
          cal: "",
          fat: "",
          cholesterol: "",
          sodium: "",
          carbs: "",
          sugars: "",
          protein: "",
        },
      ],
    },
  },
];

const DataContext = React.createContext(data);

export default DataContext;
